services:

  authwall:
    image: vbarbarosh/authwall
    restart: unless-stopped
    env_file:
      - .env
    environment:
      AUTHWALL_PUBLIC_URL: http://localhost:3000
      AUTHWALL_UPSTREAM_URL: http://echo-server:8080
      AUTHWALL_DB: mysql://authwall:authwall@mysql/authwall
      # AUTHWALL_DB: postgres://authwall:authwall@postgres/authwall
    ports:
      - 3000:3000
    volumes:
      - ./data/authwall:/app/data
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4.8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: authwall
      MYSQL_USER: authwall
      MYSQL_PASSWORD: authwall
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql

#  postgres:
#    image: postgres:17-alpine
#    restart: unless-stopped
#    environment:
#      POSTGRES_DB: authwall
#      POSTGRES_USER: authwall
#      POSTGRES_PASSWORD: authwall
#    volumes:
#      - ./data/postgres:/var/lib/postgresql/data

  echo-server:
      image: jmalloc/echo-server
      restart: unless-stopped
