public_url: ${AUTHWALL_PUBLIC_URL}

public_paths:
  # Only paths listed here are publicly accessible.
  # Default: all paths are private.
  #
  # Avoid exposing the root path (/), as it may implicitly expose
  # dependent assets (CSS, images, fonts).
  - /foo
  - /bar

  # common public files
  - /favicon.ico
  - /robots.txt
  - /humans.txt
  - /site.webmanifest

  # well-known endpoints
  - /.well-known/appspecific/com.chrome.devtools.json

target:
  url: ${AUTHWALL_TARGET_URL}
  mode: ${AUTHWALL_TARGET_MODE}

access:
  # (1) denied_emails -> deny
  # (2) allowed_emails -> allow
  # (3) denied_domains -> deny
  # (4) allowed_domains -> allow
  # - Empty fields are ignored
  # - If neither allowed_emails nor allowed_domains is set, the default action is allow
  # - If either is set, the default action is deny
  allowed_emails: ${AUTHWALL_ALLOWED_EMAILS}
  denied_emails: ${AUTHWALL_DENIED_EMAILS}
  denied_domains: ${AUTHWALL_DENIED_DOMAINS}
  allowed_domains: ${AUTHWALL_ALLOWED_DOMAINS}

cookie:
  domain: ${AUTHWALL_COOKIE_DOMAIN}
  path: ${AUTHWALL_COOKIE_PATH}
  secure: ${AUTHWALL_COOKIE_SECURE}
  same_site: ${AUTHWALL_COOKIE_SAMESITE}
  max_age_days: 30

flows:

  # I have a password
  password:
    enabled: true
    allow_username: true
    allow_email: true
    min_password_length: 8

  # Send me a link to my email
  magic_link:
    enabled: true
    mode: link_and_code # link | code | link_and_code

  # Sign in with Google
  google:
    enabled: true
    client_id: ${AUTHWALL_GOOGLE_CLIENT_ID}
    client_secret: ${AUTHWALL_GOOGLE_CLIENT_SECRET}
    redirect_url: ${AUTHWALL_GOOGLE_REDIRECT_URL}

  # Sign in with GitHub
  github:
    enabled: true
    client_id: ${AUTHWALL_GITHUB_CLIENT_ID}
    client_secret: ${AUTHWALL_GITHUB_CLIENT_SECRET}
    redirect_url: ${AUTHWALL_GITHUB_REDIRECT_URL}

mailer:
  enabled: true
  provider: ${AUTHWALL_MAILER}

  resend:
    key: ${AUTHWALL_RESEND_KEY}
    from: ${AUTHWALL_RESEND_FROM}

  mailjet:
    key: ${AUTHWALL_MAILJET_KEY}
    secret: ${AUTHWALL_MAILJET_SECRET}
    from: ${AUTHWALL_MAILJET_FROM}

  ses:
    region: ${AUTHWALL_SES_REGION}
    key: ${AUTHWALL_SES_KEY}
    secret: ${AUTHWALL_SES_SECRET}
    session_token: ${AUTHWALL_SES_SESSION_TOKEN}
    from: ${AUTHWALL_SES_FROM}

targets:
  apps.authwall.test: http://apps:8080
  echo.authwall.test: http://echo:8080
  notes.authwall.test: http://notes:8080

seed_users:

  - username: foo
    display_name: Foo
    password_hash: $2b$12$HjdTGILq./Cak9R9pTQqxODQSkmuS.vnOWVpQxo14R0tSQiqGBE0G

  - username: bar
    display_name: Bar
    password_hash: $2b$12$jxYJroE/c89SnJ8kKUwhmOpWFluDIffN5vwTZNnm26xFrTAP.Mi1y
    email:
      - bar1@authwall.test
      - bar2@authwall.test
